### ISSUE TITLE
can't build peony with Qt 5.15b2

### ISSUE THREAD

**Issue by damianatorrpm** [ukui/peony#163]
building peony latest git fails with
```
In file included from effects/border-shadow-effect.cpp:23:
effects/border-shadow-effect.h:79:18: error: field ‘m_transparent_path’ has incomplete type ‘QPainterPath’
   79 |     QPainterPath m_transparent_path;
      |                  ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/qt5/QtGui/qbrush.h:49,
                 from /usr/include/qt5/QtWidgets/qgraphicseffect.h:48,
                 from /usr/include/qt5/QtWidgets/QGraphicsEffect:1,
                 from effects/border-shadow-effect.h:26,
                 from effects/border-shadow-effect.cpp:23:
```
It works with earlier Qt than 5.15b2

**Comment by Yue-Lan** [comment]
Thanks for the building test on 5.15b2!

I will reference the new API and add a macro check for it.

**Comment by Yue-Lan** [comment]
Hello, Damian.

I added a macro check for the higher qt versions. But I could not test it on my machine... Could you please help me check it out again?

**Comment by damianatorrpm** [comment]
Hello @Yue-Lan 
You can see the build results here:
> https://build.opensuse.org/package/show/home:damianator:novos-open-rpm/peony-qt

There is on the right side succeeded and failed status, 
if you click on it you can see the build log.
